import type { RunRecord } from '../types'

/** Render a completed run as a Markdown brief. */
export function runToMarkdown(r: RunRecord): string {
  const header = `# ${r.modeEmoji} ${r.modeName} — ${r.task || 'run'}\n\n_Generated by Hive (${r.engineName} engine) · ${new Date(
    r.ts,
  ).toLocaleString()}_\n`
  const body = r.artifacts
    .map((a) => {
      const src = a.sources?.length
        ? `\n\n**Sources**\n${a.sources.map((s) => `- [${s.title}](${s.uri})`).join('\n')}`
        : ''
      return `## ${a.title}\n*${a.agentName} — ${a.agentRole}*\n\n${a.body}${src}`
    })
    .join('\n\n---\n\n')
  return `${header}\n${body}\n`
}

/** Trigger a browser download of a run as a .md file. */
export function downloadRun(r: RunRecord) {
  const blob = new Blob([runToMarkdown(r)], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  const slug = (r.task || r.modeName)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 40)
  a.href = url
  a.download = `hive-${slug || 'run'}.md`
  a.click()
  URL.revokeObjectURL(url)
}
